// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace OrderForMeProject.Models.Entities
{
    public partial class Dr_GetInfoModifyOrderResult
    {
        public int Value { get; set; }
        public string Text { get; set; }
    }
}
