// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderForMeProject.Models.Entities
{
    public partial class Logger
    {
        public int LoggerId { get; set; }
        public int UsersId { get; set; }
        public float Balance { get; set; }
        public string Type { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? IsAccept { get; set; }

        public virtual Users Users { get; set; }
    }
}