// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderForMeProject.Models.Entities
{
    public partial class Orders
    {
        public Orders()
        {
            LinkProduct = new HashSet<LinkProduct>();
        }

        public int OrdersId { get; set; }
        public int SourceBuyId { get; set; }
        public int SiteBuyId { get; set; }
        public int UsersId { get; set; }
        public int GroupProductId { get; set; }
        public float Size { get; set; }
        public float OtherFee { get; set; }
        public string Note { get; set; }
        public string Currency { get; set; }
        public int RateUsdvnd { get; set; }
        public int FeeShipping { get; set; }
        public int Tax { get; set; }
        public int FeeShippingToVn { get; set; }
        public int FeeServices { get; set; }
        public int FeeServicesOther { get; set; }
        public string PaymentType { get; set; }
        public bool IsCompleted { get; set; }
        public int StateOrderId { get; set; }
        public DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public bool? IsActive { get; set; }
        public DateTime DateBuy { get; set; }
        public int OrderRoot { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsShippingToVn { get; set; }

        public virtual GroupProduct GroupProduct { get; set; }
        public virtual SiteBuy SiteBuy { get; set; }
        public virtual SourceBuy SourceBuy { get; set; }
        public virtual StateOrder StateOrder { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<LinkProduct> LinkProduct { get; set; }
    }
}