// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderForMeProject.Models.Entities
{
    public partial class Setting
    {
        public int SettingId { get; set; }
        public string SiteName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public float Rate { get; set; }
        public float FeeServices { get; set; }
        public float FeeShippingToVn { get; set; }
    }
}