// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderForMeProject.Models.Entities
{
    public partial class SourceBuy
    {
        public SourceBuy()
        {
            Orders = new HashSet<Orders>();
        }

        public int SourceBuyId { get; set; }
        public string Name { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
    }
}