// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderForMeProject.Models.Entities
{
    public partial class VListOrder
    {
        public int OrdersId { get; set; }
        public string Fullname { get; set; }
        public float Price { get; set; }
        public int Quantity { get; set; }
        public int? TotalMoney { get; set; }
        public int RateUsdtoVnd { get; set; }
        public DateTime CreateOn { get; set; }
        public int StateOrderId { get; set; }
        public string StateName { get; set; }
        public string GroupProductName { get; set; }
    }
}